Controller/Module/BaseModuleController.php
<?php

namespace Megacoders\PageBundle\Controller\Module;

use Megacoders\PageBundle\Entity\Page;
use Megacoders\PageBundle\Entity\PageBlock;
use Megacoders\PageBundle\Model\LayoutArea;
use Megacoders\PageBundle\Model\LoadedPage;
use Megacoders\PageBundle\Model\ModuleTemplate;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Config\FileLocatorInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RouteCollection;

abstract class BaseModuleController extends Controller implements ModuleControllerInterface, RoutesConfigurableInterface
{
    /**
     * @var string
     */
    protected $mainBlockRoute;

    /**
     * @var array
     */
    protected $blockRoutes;

    /**
     * @var string
     */
    private $moduleId;

    /**
     * @var array
     */
    private $parameters;

    /**
     * @var Request
     */
    private $request;

    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * @return string
     */
    public function getModuleId()
    {
        return $this->moduleId;
    }

    /**
     * @param $moduleId
     * @return BaseModuleController
     */
    public function setModuleId($moduleId)
    {
        $this->moduleId = $moduleId;
        return $this;
    }

    /**
     * @return array
     */
    public function getModuleParameters()
    {
        return $this->parameters;
    }

    /**
     * @param string $name
     * @param mixed|null $default
     * @return mixed|null
     */
    public function getModuleParameter($name, $default = null)
    {
        return isset($this->parameters[$name]) ? $this->parameters[$name] : $default;
    }

    /**
     * @param array $parameters
     * @return BaseModuleController
     */
    public function setModuleParameters(array $parameters)
    {
        $this->parameters = [];

        foreach ($parameters as $name => $value) {
            $this->setModuleParameter($name, $value);
        }

        return $this;
    }

    /**
     * @param string $name
     * @param mixed $value
     * @return BaseModuleController
     */
    public function setModuleParameter($name, $value)
    {
        $this->parameters[$name] = $value;
        return $this;
    }

    /**
     * @param string $baseName
     * @param string $baseUrl
     * @param PageBlock $pageBlock
     * @return RouteCollection|void
     */
    public function configureRoutes($baseName, $baseUrl, PageBlock $pageBlock)
    {
    }

    /**
     * @return RouteCollection|void
     */
    public function configureServiceRoutes()
    {
    }

    /**
     * @param Request $request
     * @return Response
     */
    public function handle(Request $request) {
        $this->setModuleParameters($request->get('_parameters', []));

        $this->request = $request;

        if ($this->getActionId()) {
            $method = strtolower($this->getActionId()) .'Action';

            if (method_exists($this, $method)) {
                return $this->{$method}($request);
            }
        }

        return $this->indexAction($request);
    }

    /**
     * @param string $routeNamePostfix
     * @param array $parameters
     * @param int $referenceType
     * @return null|string
     */
    public function generateMainBlockUrl($routeNamePostfix = '', array $parameters = [],
                                         $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
    {
        try {
            return $this->generateUrl(
                $this->getBaseRouteName() .($routeNamePostfix ? '_' .$routeNamePostfix : ''),
                $parameters, $referenceType
            );

        } catch (RouteNotFoundException $e) {
            return null;
        }
    }

    /**
     * @param string $actionId
     * @param array $parameters
     * @param int $referenceType
     * @return null|string
     */
    public function generateActionUrl($actionId = 'index', array $parameters = [],
                                      $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
    {
        try {
            return $this->generateUrl($this->getActionRouteName($actionId), $parameters, $referenceType);

        } catch (RouteNotFoundException $e) {
            return null;
        }
    }

    public function generateModuleUrl($moduleId, $actionId = 'index', $routeNamePostfix = '', $parameters = [],
                                      $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
    {
        try {
            return $this->generateUrl(
                $this->getModuleRouteName($moduleId, $actionId) .($routeNamePostfix ? '_' .$routeNamePostfix : ''),
                $parameters, $referenceType);

        } catch (RouteNotFoundException $e) {
            return null;
        }
    }

    /**
     * @return string
     */
    protected function getActionId()
    {
        return $this->request->get('_action');
    }

    /**
     * @return string
     */
    protected function getTemplateId()
    {
        return $this->request->get('_template');
    }

    /**
     * @param string $action
     * @return string | null
     */
    protected function getTemplate($action)
    {
        /** @var FileLocatorInterface $fileLocator */
        $fileLocator = $this->get('file_locator');

        $class = get_class($this);
        $bundle = str_replace('\\', '', substr($class, 0, strpos($class, 'Bundle')));
        $templateIds = [$this->getTemplateId(), ModuleTemplate::DEFAULT_TEMPLATE_ID];

        foreach ($templateIds as $templateId) {
            try {
                $templatePath = sprintf('%sBundle/views/%s/%s.html.twig', $bundle, $templateId, $action);
                return $fileLocator->locate($templatePath);

            } catch (\InvalidArgumentException $e) {
                continue;
            }
        }

        return $fileLocator->locate(sprintf('%sBundle/views/%s.html.twig', $bundle, $action));
    }

    /**
     * {@inheritdoc}
     */
    protected function render($actionName, array $parameters = array(), Response $response = null)
    {
        $view = $this->getTemplate($actionName);
        $info = array_merge([
            '_page' => $this->getPage(),
            '_area' => $this->getArea(),
            '_template' => $this->getTemplateId(),
            '_parameters' => $this->getModuleParameters(),
            'title' => $this->getBlockTitle()
        ], $parameters);

        /** @var \Twig_Environment $twig */
        $twig = $this->container->has('twig') ? $this->container->get('twig') : null;
        $twigIsStrictVariables = $twig ? $twig->isStrictVariables() : null;

        if ($twigIsStrictVariables === true) {
            $twig->disableStrictVariables();
        }

        $response = parent::render($view, $info, $response);

        if ($twigIsStrictVariables === true) {
            $twig->enableStrictVariables();
        }

        return $response;
    }

    /**
     * @return string
     */
    protected function getBaseRouteName()
    {
        if (!$this->isMain()) {
            $moduleId = $this->getModuleId();

            if (isset($this->mainBlockRoute)) {
                return $this->mainBlockRoute;
            }

            /** @var Page $page */
            $page = $this->get('page.manager.page_manager')
                ->getModuleBasePage($moduleId, $this->getLocale());

            if ($page !== null) {
                $this->mainBlockRoute = $page->getRouteName();
                return $this->mainBlockRoute;
            }
        }

        return $this->request->get('_baseRoute');
    }

    /**
     * @param string $moduleId
     * @param string $actionId
     * @return string|null
     */
    protected function getModuleRouteName($moduleId, $actionId = 'index')
    {
        $routeNameKey = implode(':', [$moduleId, $actionId]);

        if (isset($this->blockRoutes[$routeNameKey])) {
            return $this->blockRoutes[$routeNameKey];
        }

        /** @var Page $page */
        $page = $this->get('page.manager.page_manager')
            ->getModuleActionPage($moduleId, $actionId, $this->getLocale());

        if ($page !== null) {
            $this->blockRoutes[$routeNameKey] = $page->getRouteName();
            return $this->blockRoutes[$routeNameKey];
        }

        $this->blockRoutes[$routeNameKey] = null;

        return null;
    }

    /**
     * @param string $actionId
     * @return string|null
     */
    protected function getActionRouteName($actionId)
    {
        return $this->getModuleRouteName($this->getModuleId(), $actionId);
    }

    /**
     * @return string
     */
    protected function getRouteName()
    {
        return $this->request->get('_route');
    }

    /**
     * @return LoadedPage
     */
    protected function getPage()
    {
        return $this->request->get('_page');
    }

    /**
     * @return LayoutArea
     */
    protected function getArea()
    {
        return $this->request->get('_area');
    }

    /**
     * @return string
     */
    protected function getBlockTitle()
    {
        return $this->request->get('_block_title');
    }

    /**
     * @return bool
     */
    protected function isMain()
    {
        return $this->getArea()->isMain();
    }

    /**
     * @return string
     */
    protected function getLocale()
    {
        return $this->request->get('_locale');
    }

    /**
     * @param mixed $object
     */
    protected function addPageExtraBreadcrumb($object)
    {
    }

    /**
     * @param mixed $object
     */
    protected function addPageMetaTitle($object)
    {
    }

    /**
     * @param Request $request
     * @return Response
     */
    abstract public function indexAction(Request $request);

}

Resources/views/Admin/Page/edit.html.twig
{% extends 'SonataAdminBundle:CRUD:edit.html.twig' %}

{% block form %}
    {{ parent() }}

    <script>
        $(function() {
            var $typeSelect = $("#{{ admin.uniqId }}_type");
            var $linkTypeSelect = $("#{{ admin.uniqId }}_linkType");
            var $linkProperties = $("#sonata-ba-field-container-{{ admin.uniqId }}_linkPage, #sonata-ba-field-container-{{ admin.uniqId }}_linkUrl");

            $typeSelect
                .on("change", function() {
                    $linkTypeSelect.trigger("change");

                    if ($typeSelect.val() === "PAGE") {
                        console.log("HIDE PROPS", $linkProperties);
                        $linkProperties.hide();
                    }
                })
                .trigger("change");
        });
    </script>
{% endblock %}

Resources/views/Admin/Page/list__action__blocks.html.twig
{% if admin.isGranted('EDIT', object) and object.type == 'PAGE' %}
    <a href="{{ path('admin_megacoders_page_page_pageblock_list', {id: object.id}) }}"
       class="btn btn-sm btn-default blocks_link"
       title="{{ 'admin.entities.page.actions.blocks'|trans }}">
        <i class="fa fa-th-large" aria-hidden="true"></i>
        {{ 'admin.entities.page.actions.blocks'|trans }}
    </a>
{% endif %}

Resources/views/Admin/Page/list__field__tree_name.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    {{ object.treeName('&#12288;&#12288;')|raw }}
{% endblock %}

Resources/views/Admin/Page/tree.html.twig
{% extends 'SonataAdminBundle:CRUD:list.html.twig' %}

{% import _self as tree %}
{% macro pages(pages, admin, rootPages) %}
    {% for page in pages %}
        <div class="admin-tree-item row">
            <div class="col-xs-12 col-md-7">
                <div class="row">
                    <div class="col-xs-1">
                        <div class="admin-tree-item-batch">
                            <input type="checkbox" name="idx[]" value="{{ admin.id(page) }}">
                        </div>
                    </div>

                    <div class="col-xs-8">
                        <div class="admin-tree-item-inner" style="padding-left: {{ page.level * 15 }}px">
                            <div class="admin-tree-item-header">{{ page.name }}</div>
                            <a href="{% if not page.published and page.type != 'LINK'%}/unpublished{% endif %}{{ page.url }}" target="_blank" class="admin-tree-item-inner_url text-muted">
                                {% if page.type == 'LINK' %}<span class="link-arrow">→</span>{% endif %}
                                {{ page.targetUrl|default('…') }}
                            </a>
                        </div>
                    </div>

                    <div class="col-xs-1">
                        <div class="admin-tree-item-inner padding-top-10">{{ page.locale }}</div>
                    </div>

                    <div class="col-xs-1">
                        <div class="admin-tree-item-inner padding-top-10 text-muted">{{ page.sortOrder }}</div>
                    </div>

                    <div class="col-xs-1">
                        <div class="admin-tree-item-inner padding-top-10">
                            {% if not page.published %}
                                <i class="fa fa-eye-slash" title="{{ 'admin.entities.page.not_published'|trans }}"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-5">
                <div class="admin-tree-item-actions btn-group pull-right">
                    {% include 'MegacodersPageBundle:Admin/Page:list__action__blocks.html.twig' with {object: page} %}
                    {% include 'SonataAdminBundle:CRUD:list__action_edit.html.twig' with {object: page} %}
                    {% include 'MegacodersAdminBundle::list__action__clone.html.twig' with {object: page} %}
                    {% include 'SonataAdminBundle:CRUD:list__action_delete.html.twig' with {object: page} %}
                </div>
            </div>
        </div>

        {% if page.children|length %}
            {{ _self.pages(page.children, admin, false) }}
        {% endif %}
    {% endfor %}
{% endmacro %}

{% block list_table %}
    <div class="col-xs-12 col-md-12">
        {% set batchactions = admin.batchactions %}
        {% if admin.hasRoute('batch') and batchactions|length %}
        <form action="{{ admin.generateUrl('batch', {'filter': admin.filterParameters}) }}" method="POST" >
            <input type="hidden" name="_sonata_csrf_token" value="{{ csrf_token }}">
            {% endif %}

            <div class="box box-primary">
                <div class="box-header">
                    <h1 class="box-title">{{ 'admin.labels.pages'|trans }}</h1>
                </div>
                <div class="box-content admin-tree">
                    {% if site is empty %}
                        <p><em>{{ 'admin.messages.site.no_sites_yet'|trans }}</em></p>
                    {% elseif pages is empty %}
                        <p><em>{{ 'admin.messages.page.no_pages_yet'|trans }}</em></p>
                    {% else %}
                        {{ tree.pages(pages, admin, true) }}
                    {% endif %}

                    {% if pages|length %}
                        {% block list_footer %}
                        <div class="box-footer">
                            <div class="form-inline clearfix">
                                {% if not app.request.isXmlHttpRequest %}
                                    <div class="pull-left">
                                        {% if admin.hasRoute('batch') and batchactions|length > 0  %}
                                            {% block batch %}
                                                <input type="hidden" name="is_tree_batch" value="true">

                                                {% block batch_actions %}
                                                    <label class="checkbox" for="{{ admin.uniqid }}_all_elements">
                                                        <input type="checkbox" name="all_elements" id="{{ admin.uniqid }}_all_elements">
                                                        {{ 'all_elements'|trans({}, 'SonataAdminBundle') }}
                                                        ({{ pages|length }})
                                                    </label>

                                                    <select name="action" style="width: auto; height: auto" class="form-control">
                                                        {% for action, options in batchactions %}
                                                            <option value="{{ action }}">{{ options.label|trans({}, options.translation_domain|default(admin.translationDomain)) }}</option>
                                                        {% endfor %}
                                                    </select>
                                                {% endblock %}

                                                    <input type="submit" class="btn btn-small btn-primary" value="{{ 'btn_batch'|trans({}, 'SonataAdminBundle') }}">
                                            {% endblock %}
                                        {% endif %}
                                    </div>

                                    <div class="pull-right">
                                        {% if admin.hasRoute('export') and admin.isGranted('EXPORT') and admin.getExportFormats()|length %}
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                                    <i class="fa fa-share-square-o" aria-hidden="true"></i>
                                                    {{ "label_export_download"|trans({}, "SonataAdminBundle") }}
                                                    <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu pull-right">
                                                    {% for format in admin.getExportFormats() %}
                                                    <li>
                                                        <a href="{{ admin.generateUrl('export', admin.modelmanager.paginationparameters(admin.datagrid, 0) + {'format' : format}) }}">
                                                            <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i>
                                                            {{ ("export_format_" ~ format)|trans({}, 'SonataAdminBundle') }}
                                                        </a>
                                                    <li>
                                                        {% endfor %}
                                                </ul>
                                            </div>
                                        {% endif %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    {% endblock %}
                    {% endif %}
                </div>
            </div>

            {% if admin.hasRoute('batch') and batchactions|length %}
        </form>
        {% endif %}
    </div>
{% endblock %}