Entity/PageBlock.php
<?php

namespace Megacoders\PageBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity
 * @ORM\Table(name="page_block")
 * @UniqueEntity(
 *     fields={"page", "areaId"},
 *     errorPath="areaId",
 *     ignoreNull=false
 * )
 */
class PageBlock
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Page", inversedBy="blocks")
     * @Assert\NotBlank()
     * @var Page
     */
    private $page;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @var string
     */
    private $areaId;

    /**
     * @ORM\ManyToOne(targetEntity="Block", inversedBy="pageBlocks")
     * @Assert\NotBlank()
     * @var Block
     */
    private $block;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @var string
     */
    private $templateId;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return PageBlock
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return Page
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * @param Page $page
     * @return PageBlock
     */
    public function setPage($page)
    {
        $this->page = $page;
        return $this;
    }

    /**
     * @return string
     */
    public function getAreaId()
    {
        return $this->areaId;
    }

    /**
     * @param string $areaId
     * @return PageBlock
     */
    public function setAreaId($areaId)
    {
        $this->areaId = $areaId;
        return $this;
    }

    /**
     * @return Block
     */
    public function getBlock()
    {
        return $this->block;
    }

    /**
     * @param Block $block
     * @return PageBlock
     */
    public function setBlock($block)
    {
        $this->block = $block;
        return $this;
    }

    /**
     * @return string
     */
    public function getTemplateId()
    {
        return $this->templateId;
    }

    /**
     * @param string $templateId
     * @return PageBlock
     */
    public function setTemplateId($templateId)
    {
        $this->templateId = $templateId;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getModuleId()
    {
        $block = $this->getBlock();
        return $block ? $block->getModuleId() : null;
    }

    /**
     * @return string
     */
    public function getActionId()
    {
        $block = $this->getBlock();
        return $block ? $block->getActionId() : null;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return implode(' » ', [$this->getPage(), $this->getBlock()]);
    }

    public function __clone()
    {
        $this->setId(null);
    }
}

Controller/Module/BaseModuleController.php
<?php

namespace Megacoders\PageBundle\Controller\Module;

use Megacoders\PageBundle\Entity\Page;
use Megacoders\PageBundle\Entity\PageBlock;
use Megacoders\PageBundle\Model\LayoutArea;
use Megacoders\PageBundle\Model\LoadedPage;
use Megacoders\PageBundle\Model\ModuleTemplate;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Config\FileLocatorInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RouteCollection;

abstract class BaseModuleController extends Controller implements ModuleControllerInterface, RoutesConfigurableInterface
{
    /**
     * @var string
     */
    protected $mainBlockRoute;

    /**
     * @var array
     */
    protected $blockRoutes;

    /**
     * @var string
     */
    private $moduleId;

    /**
     * @var array
     */
    private $parameters;

    /**
     * @var Request
     */
    private $request;

    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * @return string
     */
    public function getModuleId()
    {
        return $this->moduleId;
    }

    /**
     * @param $moduleId
     * @return BaseModuleController
     */
    public function setModuleId($moduleId)
    {
        $this->moduleId = $moduleId;
        return $this;
    }

    /**
     * @return array
     */
    public function getModuleParameters()
    {
        return $this->parameters;
    }

    /**
     * @param string $name
     * @param mixed|null $default
     * @return mixed|null
     */
    public function getModuleParameter($name, $default = null)
    {
        return isset($this->parameters[$name]) ? $this->parameters[$name] : $default;
    }

    /**
     * @param array $parameters
     * @return BaseModuleController
     */
    public function setModuleParameters(array $parameters)
    {
        $this->parameters = [];

        foreach ($parameters as $name => $value) {
            $this->setModuleParameter($name, $value);
        }

        return $this;
    }

    /**
     * @param string $name
     * @param mixed $value
     * @return BaseModuleController
     */
    public function setModuleParameter($name, $value)
    {
        $this->parameters[$name] = $value;
        return $this;
    }

    /**
     * @param string $baseName
     * @param string $baseUrl
     * @param PageBlock $pageBlock
     * @return RouteCollection|void
     */
    public function configureRoutes($baseName, $baseUrl, PageBlock $pageBlock)
    {
    }

    /**
     * @return RouteCollection|void
     */
    public function configureServiceRoutes()
    {
    }

    /**
     * @param Request $request
     * @return Response
     */
    public function handle(Request $request) {
        $this->setModuleParameters($request->get('_parameters', []));

        $this->request = $request;

        if ($this->getActionId()) {
            $method = strtolower($this->getActionId()) .'Action';

            if (method_exists($this, $method)) {
                return $this->{$method}($request);
            }
        }

        return $this->indexAction($request);
    }

    /**
     * @param string $routeNamePostfix
     * @param array $parameters
     * @param int $referenceType
     * @return null|string
     */
    public function generateMainBlockUrl($routeNamePostfix = '', array $parameters = [],
                                         $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
    {
        try {
            return $this->generateUrl(
                $this->getBaseRouteName() .($routeNamePostfix ? '_' .$routeNamePostfix : ''),
                $parameters, $referenceType
            );

        } catch (RouteNotFoundException $e) {
            return null;
        }
    }

    /**
     * @param string $actionId
     * @param array $parameters
     * @param int $referenceType
     * @return null|string
     */
    public function generateActionUrl($actionId = 'index', array $parameters = [],
                                      $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
    {
        try {
            return $this->generateUrl($this->getActionRouteName($actionId), $parameters, $referenceType);

        } catch (RouteNotFoundException $e) {
            return null;
        }
    }

    public function generateModuleUrl($moduleId, $actionId = 'index', $routeNamePostfix = '', $parameters = [],
                                      $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
    {
        try {
            return $this->generateUrl(
                $this->getModuleRouteName($moduleId, $actionId) .($routeNamePostfix ? '_' .$routeNamePostfix : ''),
                $parameters, $referenceType);

        } catch (RouteNotFoundException $e) {
            return null;
        }
    }

    /**
     * @return string
     */
    protected function getActionId()
    {
        return $this->request->get('_action');
    }

    /**
     * @return string
     */
    protected function getTemplateId()
    {
        return $this->request->get('_template');
    }

    /**
     * @param string $action
     * @return string | null
     */
    protected function getTemplate($action)
    {
        /** @var FileLocatorInterface $fileLocator */
        $fileLocator = $this->get('file_locator');

        $class = get_class($this);
        $bundle = str_replace('\\', '', substr($class, 0, strpos($class, 'Bundle')));
        $templateIds = [$this->getTemplateId(), ModuleTemplate::DEFAULT_TEMPLATE_ID];

        foreach ($templateIds as $templateId) {
            try {
                $templatePath = sprintf('%sBundle/views/%s/%s.html.twig', $bundle, $templateId, $action);
                return $fileLocator->locate($templatePath);

            } catch (\InvalidArgumentException $e) {
                continue;
            }
        }

        return $fileLocator->locate(sprintf('%sBundle/views/%s.html.twig', $bundle, $action));
    }

    /**
     * {@inheritdoc}
     */
    protected function render($actionName, array $parameters = array(), Response $response = null)
    {
        $view = $this->getTemplate($actionName);
        $info = array_merge([
            '_page' => $this->getPage(),
            '_area' => $this->getArea(),
            '_template' => $this->getTemplateId(),
            '_parameters' => $this->getModuleParameters(),
            'title' => $this->getBlockTitle()
        ], $parameters);

        /** @var \Twig_Environment $twig */
        $twig = $this->container->has('twig') ? $this->container->get('twig') : null;
        $twigIsStrictVariables = $twig ? $twig->isStrictVariables() : null;

        if ($twigIsStrictVariables === true) {
            $twig->disableStrictVariables();
        }

        $response = parent::render($view, $info, $response);

        if ($twigIsStrictVariables === true) {
            $twig->enableStrictVariables();
        }

        return $response;
    }

    /**
     * @return string
     */
    protected function getBaseRouteName()
    {
        if (!$this->isMain()) {
            $moduleId = $this->getModuleId();

            if (isset($this->mainBlockRoute)) {
                return $this->mainBlockRoute;
            }

            /** @var Page $page */
            $page = $this->get('page.manager.page_manager')
                ->getModuleBasePage($moduleId, $this->getLocale());

            if ($page !== null) {
                $this->mainBlockRoute = $page->getRouteName();
                return $this->mainBlockRoute;
            }
        }

        return $this->request->get('_baseRoute');
    }

    /**
     * @param string $moduleId
     * @param string $actionId
     * @return string|null
     */
    protected function getModuleRouteName($moduleId, $actionId = 'index')
    {
        $routeNameKey = implode(':', [$moduleId, $actionId]);

        if (isset($this->blockRoutes[$routeNameKey])) {
            return $this->blockRoutes[$routeNameKey];
        }

        /** @var Page $page */
        $page = $this->get('page.manager.page_manager')
            ->getModuleActionPage($moduleId, $actionId, $this->getLocale());

        if ($page !== null) {
            $this->blockRoutes[$routeNameKey] = $page->getRouteName();
            return $this->blockRoutes[$routeNameKey];
        }

        $this->blockRoutes[$routeNameKey] = null;

        return null;
    }

    /**
     * @param string $actionId
     * @return string|null
     */
    protected function getActionRouteName($actionId)
    {
        return $this->getModuleRouteName($this->getModuleId(), $actionId);
    }

    /**
     * @return string
     */
    protected function getRouteName()
    {
        return $this->request->get('_route');
    }

    /**
     * @return LoadedPage
     */
    protected function getPage()
    {
        return $this->request->get('_page');
    }

    /**
     * @return LayoutArea
     */
    protected function getArea()
    {
        return $this->request->get('_area');
    }

    /**
     * @return string
     */
    protected function getBlockTitle()
    {
        return $this->request->get('_block_title');
    }

    /**
     * @return bool
     */
    protected function isMain()
    {
        return $this->getArea()->isMain();
    }

    /**
     * @return string
     */
    protected function getLocale()
    {
        return $this->request->get('_locale');
    }

    /**
     * @param mixed $object
     */
    protected function addPageExtraBreadcrumb($object)
    {
    }

    /**
     * @param mixed $object
     */
    protected function addPageMetaTitle($object)
    {
    }

    /**
     * @param Request $request
     * @return Response
     */
    abstract public function indexAction(Request $request);

}

Resources/views/Admin/PageBlock/edit.html.twig
{% extends 'SonataAdminBundle:CRUD:edit.html.twig' %}

{% block form %}
    {{ parent() }}

    <script>
        $(function() {
            var $moduleSelect = $("#{{ admin.uniqId }}_moduleId");
            var $blockSelect = $("#{{ admin.uniqId }}_block");
            var $templateIdSelect = $("#{{ admin.uniqId }}_templateId");

            $moduleSelect.on("change", function updateBlocks() {
                var moduleId = $(this).val();

                // Populate block select.
                $blockSelect
                        .attr("disabled", true)
                        .select2("val", "")
                        .empty();

                $.ajax({
                    method: "POST",
                    url: "{{ admin.generateUrl('module_blocks') }}",
                    data: {
                        "{{ admin.idParameter }}": "{{ object.id }}",
                        moduleId: moduleId,
                        uniqid: "{{ admin.uniqid }}"
                    },
                    success: function(response) {
                        $.each(response, function(id, block) {
                            $blockSelect.append($("<option/>", {
                                value: id,
                                text: block.name,
                                selected: block.selected
                            }));
                        });

                        $blockSelect
                                .removeAttr("disabled")
                                .trigger("change.select2");
                    },
                    error: function(error) {
                        $blockSelect.attr("disabled", true);

                        console.log("Error get blocks for module with ID = " + moduleId, error);
                    }
                });

                // Populate block template select.
                $templateIdSelect
                    .attr("disabled", true)
                    .select2("val", "")
                    .empty();

                $.ajax({
                    method: "POST",
                    url: "{{ admin.generateUrl('module_templates') }}",
                    data: {
                        "{{ admin.idParameter }}": "{{ object.id }}",
                        moduleId: moduleId,
                        uniqid: "{{ admin.uniqid }}"
                    },
                    success: function(response) {
                        $.each(response, function(id, template) {
                            $templateIdSelect.append($("<option/>", {
                                value: id,
                                text: template.name,
                                selected: template.selected
                            }));
                        });

                        $templateIdSelect
                            .removeAttr("disabled")
                            .trigger("change.select2");
                    },
                    error: function(error) {
                        $templateIdSelect.attr("disabled", true);

                        console.log("Error get templates for module with ID = " + moduleId, error);
                    }
                });
            });

            $moduleSelect.trigger("change");
        });
    </script>
{% endblock %}

Resources/views/Admin/PageBlock/grid.html.twig
{% extends 'SonataAdminBundle:CRUD:list.html.twig' %}

{% block stylesheets %}
    {{ parent() }}

    {% stylesheets '@MegacodersPageBundle/Resources/assets/scss/admin.scss' filter="scssphp" output="bundles/megacoderspage/css/admin-theme.css"%}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}

{% block list_table %}
    <table class="page-layout-grid">
        {% for row in rows %}
            <tr>
                {% for cell in row %}
                    <td colspan="{{ cell.area.width }}" rowspan="{{ cell.area.height }}"{% if cell.area.isMain %} class="main"{% endif %}>
                        <div class="layout-cell">
                            <div class="layout-cell-inner">

                                {% if cell.contentDescription is not empty %}
                                    <div class="cell-block cell-block_content">
                                        <a href="{{ cell.contentDescription.url }}" title="{{ 'admin.entities.page_block._actions.edit_content'|trans }}">
                                            {{ cell.contentDescription.name }}
                                        </a>
                                    </div>
                                {% endif %}

                                {% if cell.module is not empty %}
                                    <div class="cell-block cell-block_module">
                                        <a href="{{ path('admin_megacoders_page_block_edit', {id: cell.block.block.id}) }}" title="{{ 'admin.entities.page_block._actions.edit_block'|trans }}">
                                            {{ cell.module.name|trans }} » {{ cell.action.name|trans }}
                                        </a>
                                    </div>
                                {% endif %}


                                <div class="cell-block cell-block_block">
                                    {% if cell.block is not empty %}
                                        <a href="{{ path('admin_megacoders_page_page_pageblock_delete', {id: page.id, childId: cell.block.id}) }}" title="{{ 'admin.entities.page_block._actions.unbind'|trans }}" class="offside">
                                            <i class="fa fa-unlink"></i>
                                        </a>
                                        <a href="{{ path('admin_megacoders_page_page_pageblock_edit', {id: page.id, childId: cell.block.id, areaId: cell.area.id}) }}" title="{{ 'admin.entities.page_block._actions.edit_binding'|trans }}">
                                            {{ cell.block.block.name }}
                                        </a>
                                    {% else %}
                                        <a href="{{ path('admin_megacoders_page_page_pageblock_create', {id: page.id, areaId: cell.area.id}) }}" title="{{ 'admin.entities.page_block._actions.bind'|trans }}" class="offside">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a href="{{ path('admin_megacoders_page_page_pageblock_create', {id: page.id, areaId: cell.area.id}) }}" title="{{ 'admin.entities.page_block._actions.bind'|trans }}">
                                            {{ 'admin.entities.page_block._actions.bind'|trans }}
                                        </a>
                                    {% endif %}
                                </div>

                                <div class="cell-block cell-block_area">{{ cell.area.name|trans }}</div>
                            </div>
                        </div>
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

Resources/views/Admin/PageBlock/list__field__area.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    {{ admin.getArea(object, value)|trans }}
{% endblock %}

Resources/views/Admin/PageBlock/list__field__block.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    {{ value.name }}<br/>
    <i class="text-muted">{{ value.module }}</i>
{% endblock %}